---
- name: Ensure liquidator repository is checked out
  git:
    repo: 'https://github.com/bperekitko/liquidator-v2.git'
    dest: '{{ app_home }}'
- name: Ensure dependencies are installed
  shell: '. {{ nvm_home }}/nvm.sh && npm i'
  args:
    chdir: '{{ app_home }}'
    executable: /bin/bash
- name: Copy environment file template
  template:
    src: .env.j2
    dest: '{{ app_home }}/.env'
