- name: Ensure curl is installed
  become: true
  package:
    name: curl
    state: present
- name: Ensure git is installed
  become: true
  package:
    name: git
    state: present
- name: Ensure nvm is installed
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
  args:
    warn: no
    creates: '{{ nvm_home }}/nvm.sh'
- name: Ensure Node.js is installed
  shell: '. {{ nvm_home }}/nvm.sh && nvm install 10'
  args:
    creates: '{{ nvm_home }}/versions/node'
    executable: /bin/bash
